# Generated by Django 4.1 on 2022-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField(auto_now_add=True)),
                ('LoanTaken', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('EMIMonth', models.CharField(blank=True, max_length=100, null=True)),
                ('EMIAmount', models.IntegerField()),
                ('Paid', models.BooleanField()),
                ('Proof', models.FileField(blank=True, null=True, upload_to='Loans/')),
            ],
            options={
                'verbose_name_plural': 'Loans',
            },
        ),
    ]
