# Generated by Django 4.1 on 2022-08-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParterName', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(blank=True, null=True)),
                ('Amount', models.IntegerField()),
                ('Paidby', models.CharField(blank=True, max_length=100, null=True)),
                ('Proof', models.FileField(blank=True, null=True, upload_to='Food/')),
            ],
            options={
                'verbose_name_plural': 'Food',
            },
        ),
    ]
