# Generated by Django 4.1 on 2022-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TravelledIn', models.CharField(max_length=100)),
                ('Time', models.DateField(blank=True, null=True)),
                ('Amount', models.IntegerField()),
                ('Proof', models.FileField(blank=True, null=True, upload_to='Travels/')),
            ],
            options={
                'verbose_name_plural': 'Travels',
            },
        ),
        migrations.AlterField(
            model_name='food',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='FoodData/'),
        ),
    ]
