# Generated by Django 4.1 on 2022-08-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_travel_alter_food_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeExpanses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=100)),
                ('PurchasedFrom', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.DateField(blank=True, null=True)),
                ('Amount', models.IntegerField()),
                ('Proof', models.FileField(blank=True, null=True, upload_to='HomeExpanses/')),
            ],
            options={
                'verbose_name_plural': 'Home Expanses',
            },
        ),
    ]
