# Generated by Django 4.1 on 2022-08-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rentandutilities_rename_homeexpanses_shopping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentandutilities',
            old_name='ItemName',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='rentandutilities',
            old_name='PurchasedFrom',
            new_name='PaidTo',
        ),
    ]
