# Generated by Django 4.1 on 2022-08-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_itemname_rentandutilities_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='Shopping/'),
        ),
    ]
