# Generated by Django 4.1 on 2022-08-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_author_rentandutilities_user_food_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='Loans/%Y/%m/%d'),
        ),
    ]
