# Generated by Django 4.1 on 2022-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_loan_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='FoodData/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='Prescription',
            field=models.FileField(blank=True, null=True, upload_to='Medical/Prescription/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='Medical/Bills/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='rentandutilities',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='RentUtilities/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='Shopping/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='Travels/%Y/%m/%d'),
        ),
    ]
