# Generated by Django 4.1 on 2022-08-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_food_proof_alter_medical_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateField(blank=True, null=True)),
                ('Amount', models.IntegerField()),
                ('Proof', models.FileField(blank=True, null=True, upload_to='OtherExpenses/%Y/%m/%d')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OtherExpenses',
            },
        ),
    ]
