# Generated by Django 4.1 on 2022-08-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_otherexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
