# Generated by Django 4.1 on 2022-08-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='Status',
            field=models.CharField(choices=[('new', 'NEW'), ('resolved', 'RESOLVED'), ('inprogress', 'INPROGRESS'), ('cancelled', 'CANCELLED')], default='new', max_length=100),
        ),
    ]
