# Generated by Django 4.1 on 2022-08-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_support_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='Message',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='support',
            name='Comment',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
