# Generated by Django 4.1 on 2022-08-28 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_support_time_alter_support_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodLimit', models.IntegerField(default=0)),
                ('TravelLimit', models.IntegerField(default=0)),
                ('RentandUtilitiesLimit', models.IntegerField(default=0)),
                ('ShoppingLimit', models.IntegerField(default=0)),
                ('MedicalLimit', models.IntegerField(default=0)),
                ('OtherExpensesLimit', models.IntegerField(default=0)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salary Credited',
            },
        ),
    ]
