# Generated by Django 4.1 on 2022-08-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_thresholds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thresholds',
            options={'verbose_name_plural': 'User Thresholds'},
        ),
    ]
